apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-configmap
  namespace: music
data:
  PORT: "4533"
  TZ: "America/Chicago"
  ND_LOGLEVEL: "debug"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-configmap
  namespace: music
data:
  PORT: "8081"
  TZ: "America/Chicago"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feishin-configmap
  namespace: music
data:
  PORT: "9180"
  TZ: "America/Chicago"
  SERVER_NAME: "pi"
  SERVER_LOCK: "true"
  SERVER_TYPE: "navidrome"
  SERVER_URL: "http://localhost:4533"
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
