apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome

    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000

      containers:
        - name: navidrome
          image: deluan/navidrome:pr-4732
          ports:
            - containerPort: 4533
              protocol: TCP
          envFrom:
            - configMapRef:
                name: navidrome-configmap
            - secretRef:
                name: nd-lastfm.yaml

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: navidrome-data
              mountPath: /data
            - name: music
              mountPath: /music

      volumes:
        - name: navidrome-data
          persistentVolumeClaim:
            claimName: navidrome-data-pvc
        - name: music
          persistentVolumeClaim:
            claimName: music-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser

    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000

      containers:
        - name: filebrowser
          image: hurlenko/filebrowser:v2.51.2
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: filebrowser-configmap

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: filebrowser-config
              mountPath: /config
            - name: music
              mountPath: /data

      volumes:
        - name: filebrowser-config
          persistentVolumeClaim:
            claimName: filebrowser-config-pvc
        - name: music
          persistentVolumeClaim:
            claimName: music-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feishin
  namespace: music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feishin
  template:
    metadata:
      labels:
        app: feishin

    spec:
      containers:
        - name: feishin
          image: ghcr.io/jeffvli/feishin:0.22.0
          ports:
            - containerPort: 9180
              protocol: TCP
          envFrom:
            - configMapRef:
                name: feishin-configmap
