apiVersion: apps/v1
kind: Deployment
metadata:
  name: music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music

    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000

      containers:
        - name: navidrome
          image: deluan/navidrome:pr-4732
          ports:
            - containerPort: 4533
              protocol: TCP
          envFrom:
            - configMapRef:
                name: navidrome-configmap

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: navidrome-data
              mountPath: /data
            - name: music
              mountPath: /music

        - name: feishin
          image: ghcr.io/jeffvli/feishin:v0.22.0
          ports:
            containerPort: 9180
            protocol: TCP
          envFrom:
            - configMapRef:
                name: feishin-configmap

          securityContext:
            allowPrivilegeEscalation: false

        - name: filebrowser
          image: hurlenko/filebrowser:v2.50.0
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: filebrowser-configmap

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: filebrowser-config
              mountPath: /config
            - name: music
              mountPath: /data

      volumes:
        - name: navidrome-data
          persistentVolumeClaim:
            claimName: navidrome-data-pvc
        - name: music
          persistentVolumeClaim:
            claimName: music-pvc
        - name: filebrowser-config
          persistentVolumeClaim:
            claimName: filebrowser-config-pvc
