apiVersion: v1
kind: Service
metadata:
  name: navidrome
spec:
  selector:
    app: music
  ports:
    - port: 4533
      targetPort: 4533
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  selector:
    app: music
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
