apiVersion: v1
kind: Service
metadata:
  name: navidrome
spec:
  selector:
    app: navidrome
  ports:
    - port: 4533
      targetPort: 4533
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: feishin
spec:
  selector:
    app: feishin
  ports:
    - port: 9180
      targetPort: 9180
  type: ClusterIP
