apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trips
resources:
  - ../../base/trips
  - cloudflare.yaml
  - tunnel-credentials.yaml
  - trips-app-users.yaml
  - ghcr-secret.yaml
